require('dotenv').config()
const express = require('express')
const app = express()
const morgan = require('morgan')
const cookieParser = require('cookie-parser')
const passport = require('passport')
require('./config/mongodb_config')
require('./config/passport_config')
const cors = require('cors')

app.use(cors({origin: true, credentials: true}))
app.use(morgan('dev'))
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(passport.initialize())
app.use(cookieParser())

app.use('/settings', require('./routes/settingRoutes'))
app.use('/auth', require('./routes/authRoutes'))
app.use('/tweet', require('./routes/tweetRoutes'))

app.listen(8080, () => console.log('server running on port 8080'))
